name: Trigger Portfolio Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portfolio Deploy Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: itsleaheye/Portfolio
          event-type: trigger-portfolio-build
